### ISSUE TITLE
Meta-release

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#24]
## How would it work?

We'd click a single job:
 
- [x] the job needs to have passed parameters (checkboxes, comboboxes etc.)
   - name of the branch for `spring-cloud-release` (e.g. greenich - or however you type it)
      - if none is passed it will assume `master` branch.
   - map of versions (e.g. `spring-cloud-sleuth=2.1.0.RELEASE`)
      - we can already use `releaser.fetch-versions-from-git=false` and pass all properties manually via the `releaser.fixed-versions` map
- [x] create a branch for the release for `spring-cloud-release` (e.g. greenich)
- [x] update all versions in `spring-cloud-release`
- [x] iterate over projects in the order presented in properties of `spring-cloud-release` dependencies module install them, upload them to staging, etc.
    - since we’re installing we don’t have to wait for sync
- [x] once all projects got built and uploaded we can click to sync to central

additional features:
- [x] start from a project (e.g. sleuth failed, so after fixing it we want to continue from Sleuth)
- [x] add task skipping options
- [ ] perform certain tasks once only (generation of templates, tickets sending etc.)
- [ ] execute some tests against staging from sonatype
- [ ] publishing the release docs
- [ ] file a issue to initilizr in a similar way we do with guides

**Comment by spencergibb** [comment]
That way each project 'lead' could say, project x is good and when all are good, one person does the release.

**Comment by marcingrzejszczak** [comment]
There is one small problem which is the promotion of artifacts from sonatype to central. We can of course automate this but we will have to introduce a waiting period (or rather pinging central to see if the artifact is already there). Our libs require the JARs to be available in Maven Central before their release process gets executed... So the release process can be pretty lengthy (which is not a problem of course)

**Comment by spencergibb** [comment]
This is working
